import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import Navbar from "./Navbar";

const inter = localFont({ src: "../public/fonts/Gandom-FD.woff2" });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" data-theme="dark" dir="rtl" className=" max-w-full ">
      <body className={inter.className}>
        <Navbar />
        <main className="container my-5">{children}</main>
      </body>
    </html>
  );
}
